### ISSUE TITLE
gradle needs to be 1.3.0

### ISSUE THREAD

**Issue by nicolasvahidzein** [heywhy/flutter-pusher-client#1]
is there a way we can increase the graddle requirement to 1.3.0, it's not compiling because it's set to 1.2.7

thanks.

**Comment by heywhy** [comment]
Hello, thanks for the hint. I assume you are referring to the Kotlin plugin version used in the gradle.build file. I've updated the version to 1.3.61 (which is the latest) and it builds just fine. So I need you to confirm that you're referring to the Kotlin version, so that I make a release as soon as you confirm.

Atanda Rasheed

**Comment by nicolasvahidzein** [comment]
thank you i will pull the new  version and try and tell you.

**Comment by heywhy** [comment]
A release (v0.2.1) has been made to fix the Kotlin issue, you should run `flutter pub upgrade` to get the new release. Once you've tried it and it's fine, please signify so I can close this issue. Thank you.

Atanda Rasheed

**Comment by gopalkriagg** [comment]
It works now! 
`How to install` section still have old version written there: https://pub.dev/packages/flutter_pusher_client#-readme-tab-
