### ISSUE TITLE
ios not working

### ISSUE THREAD

**Issue by lkloon123** [heywhy/flutter-pusher-client#2]
```
-> Fetching podspec for `flutter_pusher_client` from `.symlinks/plugins/flutter_pusher_client/ios`
[!] No podspec found for `flutter_pusher_client` in `.symlinks/plugins/flutter_pusher_client/ios`
```

**Comment by pkcell** [comment]
Fetching podspec for `flutter_pusher_client` from `.symlinks/plugins/flutter_pusher_client/ios`
[!] No podspec found for `flutter_pusher_client` in `.symlinks/plugins/flutter_pusher_client/ios`

**Comment by heywhy** [comment]
I'll suggest you guys have a look at #6

**Comment by heywhy** [comment]
I'm sorry the iOS support came in late because I had to learn swift to be able to support iOS, since I couldn't find a contributor build the support. But I'm glad to announce that a new version of [flutter_pusher_client](https://github.com/heywhy/flutter-pusher-client) has been released. So you are advised to upgrade to the latest version and also upgrade your flutter tools.
