### ISSUE TITLE
How can i solve this issue on IOS?

### ISSUE THREAD

**Issue by junaidhashmi** [heywhy/flutter-pusher-client#8]
Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `flutter_pusher_client` from `.symlinks/plugins/flutter_pusher_client/ios`
    [!] The `flutter_pusher_client` pod failed to validate due to 1 error:
        - ERROR | attributes: Missing required attribute `homepage`.
        - WARN  | license: Missing license type.
        - WARN  | description: The description is equal to the summary.
        - WARN  | [iOS] keys: Missing primary key for `source` attribute. The acceptable ones are: `git, hg, http, svn`.

**Comment by jgalindosl** [comment]
I submitted a pull request https://github.com/heywhy/flutter-pusher-client/pull/9 to fix this issue.

**Comment by junaidhashmi** [comment]
You mean it's working in iOS now?

**Comment by heywhy** [comment]
I'm sorry the iOS support came in late because I had to learn swift to be able to support iOS, since I couldn't find a contributor build the support. But I'm glad to announce that a new version of [flutter_pusher_client](https://github.com/heywhy/flutter-pusher-client) has been released. So you are advised to upgrade to the latest version and also upgrade your flutter tools.
